# Generated by Django 4.0.1 on 2022-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dataCreation',
            new_name='dateCreation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dataCreation',
            new_name='dateCreation',
        ),
    ]
