# Generated by Django 4.0.1 on 2022-02-27 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0003_postcategory_subscribers_alter_post_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.category'),
        ),
    ]
