# Generated by Django 4.0.1 on 2022-03-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_category_subscribers_remove_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newapp.category'),
        ),
    ]
